### ISSUE TITLE
Update pip

### ISSUE THREAD

**Issue by RalfMackenbach** [landreman/pyQSC#21]
Hi!

This is only a minor issue - I was using the recommended install of pyQSC (i.e. `pip install qsc`), but some of the newer configurations were missing (e.g. `Qsc.from_paper('2022 QA', nphi=1001)` was not found). I guess it's only a matter of updating the pip version? Anyway, using the source directly alleviated this issue for me.

cheers,
Ralf

**Comment by rogeriojorge** [comment]
I am going to assign this to Matt for him to update the version in PyPI once he comes back from vacation.

**Comment by landreman** [comment]
I just made a new release 0.1.2 on pypi with the latest version of the code, including the configurations from the 2022 paper.
